package com.stockscreener.screenerapi.entity;

public enum Industry {
	AUTO_AND_AUTO_ANCILLARY, BANKING_AND_FINANCIAL_SERVICES, FMCG, INFORMATION_TECHNOLOGY,
    MEDIA_AND_ENTERTAINMENT, PHARMA_AND_HEALTHCARE, RETAIL, REAL_ESTATE, TELECOM, TRAVEL_AND_TOURISM, OTHERS
}
